# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 2
set_param xicom.use_bs_reader 1
set_msg_config  -id {Synth 8-614}  -string {{WARNING: [Synth 8-614] signal 'tensP1' is read in the process but is not in the sensitivity list [C:/Users/joosv/OneDrive/Bureaublad/Vakken/Digitale Elektronica/Pong/Pong.srcs/sources_1/new/Scorebord.vhd:37]}}  -suppress 
set_msg_config  -id {Synth 8-614}  -string {{WARNING: [Synth 8-614] signal 'tensP2' is read in the process but is not in the sensitivity list [C:/Users/joosv/OneDrive/Bureaublad/Vakken/Digitale Elektronica/Pong/Pong.srcs/sources_1/new/Scorebord.vhd:37]}}  -suppress 
set_msg_config  -id {Synth 8-327}  -string {{WARNING: [Synth 8-327] inferring latch for variable 'tensP2_reg' [C:/Users/joosv/OneDrive/Bureaublad/Vakken/Digitale Elektronica/Pong/Pong.srcs/sources_1/new/Scorebord.vhd:68]}}  -suppress 
set_msg_config  -id {Synth 8-327}  -string {{WARNING: [Synth 8-327] inferring latch for variable 'tensP1_reg' [C:/Users/joosv/OneDrive/Bureaublad/Vakken/Digitale Elektronica/Pong/Pong.srcs/sources_1/new/Scorebord.vhd:40]}}  -suppress 
set_msg_config  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (Score/tensP1_reg[3]) is unused and will be removed from module Pong.}}  -suppress 
set_msg_config  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (Score/tensP1_reg[2]) is unused and will be removed from module Pong.}}  -suppress 
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/joosv/OneDrive/Bureaublad/Vakken/Digitale Elektronica/Pong/Pong.cache/wt} [current_project]
set_property parent.project_path {C:/Users/joosv/OneDrive/Bureaublad/Vakken/Digitale Elektronica/Pong/Pong.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo {c:/Users/joosv/OneDrive/Bureaublad/Vakken/Digitale Elektronica/Pong/Pong.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  {C:/Users/joosv/OneDrive/Bureaublad/Vakken/Digitale Elektronica/Pong/Pong.srcs/sources_1/new/Audio.vhd}
  {C:/Users/joosv/OneDrive/Bureaublad/Vakken/Digitale Elektronica/Pong/Pong.srcs/sources_1/new/Background.vhd}
  {C:/Users/joosv/OneDrive/Bureaublad/Vakken/Digitale Elektronica/Pong/Pong.srcs/sources_1/new/Ball.vhd}
  {C:/Users/joosv/OneDrive/Bureaublad/Vakken/Digitale Elektronica/Pong/Pong.srcs/sources_1/new/Borders.vhd}
  {C:/Users/joosv/OneDrive/Bureaublad/Vakken/Digitale Elektronica/Pong/Pong.srcs/sources_1/new/PongBat.vhd}
  {C:/Users/joosv/OneDrive/Bureaublad/Vakken/Digitale Elektronica/Pong/Pong.srcs/sources_1/new/Random.vhd}
  {C:/Users/joosv/OneDrive/Bureaublad/Vakken/Digitale Elektronica/Pong/Pong.srcs/sources_1/new/Scorebord.vhd}
  {C:/Users/joosv/OneDrive/Bureaublad/Vakken/Digitale Elektronica/Pong/Pong.srcs/sources_1/new/VGA.vhd}
  {C:/Users/joosv/OneDrive/Bureaublad/Vakken/Digitale Elektronica/Pong/Pong.srcs/sources_1/new/Pong.vhd}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/joosv/OneDrive/Bureaublad/Vakken/Digitale Elektronica/Pong/Pong.srcs/constrs_1/new/A7100t.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/joosv/OneDrive/Bureaublad/Vakken/Digitale Elektronica/Pong/Pong.srcs/constrs_1/new/A7100t.xdc}}]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top Pong -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Pong.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Pong_utilization_synth.rpt -pb Pong_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
